server:
    port: 18301
spring:
    application:
        name: demo-provider # Spring 应用名
    cloud:
        nacos:
            # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
            discovery:
                server-addr: 127.0.0.1:9527 # Nacos 服务器地址
                service: ${spring.application.name} # 注册到 Nacos 的服务名。默认值为 ${spring.application.name}。


# es配置
es:
    service:
        default:
            ip: 127.0.0.1:9200
            scheme: 
